#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Oct  8 21:17:29 2009

import wx, time, os, random

# begin wxGlade: extracode
# end wxGlade



class repeater_gui(wx.Frame):
    def __init__(self, parent = None, id = -1, title = "Field Team"):
        # begin wxGlade: MyFrame1.__init__
#        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, parent, id, title)
        self.picture = wx.StaticBitmap(self, -1, wx.Bitmap("./heli_hang.jpg", wx.BITMAP_TYPE_ANY))
        self.lat_label = wx.StaticText(self, -1, "Latitude", style=wx.ALIGN_RIGHT)
        self.lat_ctrl = wx.TextCtrl(self, -1, "")
        self.lon_label = wx.StaticText(self, -1, "Longitude", style=wx.ALIGN_RIGHT)
        self.lon_ctrl = wx.TextCtrl(self, -1, "")
        self.age_label = wx.StaticText(self, -1, "Beacon Age", style=wx.ALIGN_RIGHT)
        self.age_ctrl = wx.TextCtrl(self, -1, "")
        self.msg_label = wx.StaticText(self, -1, "Messages")
        self.msg_panel = wx.Panel(self, -1, style = wx.BORDER_SUNKEN)
        self.msg_ctrl = wx.StaticText(self.msg_panel, -1, "")
        self.ack_button = wx.Button(self, -1, "Acknowledge")
        self.act_button = wx.Button(self, -1, "Activate")

        self.lat_ctrl.SetEditable(False)
        self.lon_ctrl.SetEditable(False)
        self.age_ctrl.SetEditable(False)

        self.msgs = []

        self.timer = wx.Timer(self, -1)

        self.timer.Start(500)
        self.Bind(wx.EVT_TIMER, self.OnTimer)

        self.__set_properties()
        self.__do_layout()
        
        self.Bind(wx.EVT_BUTTON, self.go, id=self.act_button.GetId())
        self.Bind(wx.EVT_BUTTON, self.ack, id=self.ack_button.GetId())
        
        self.dir = ['North', 'West', 'South', 'East']
        self.counter = 0

        self.Centre()
        self.Show(True)
        # end wxGlade

    def ack(self, event):
        self.update_msg_ctrl('Acknowledged....')

    def go(self, event):
        self.update_msg_ctrl('Activated.....')


    def update_msg_ctrl(self, value):
        self.msgs.append(value)
        msg = "\n".join(self.msgs)
        if len(self.msgs) == 25:
            self.msgs.pop(0)
        self.msg_ctrl.SetLabel(msg)


    def OnTimer(self, event):
        if os.path.exists('gui_beacon_data'):
            f = open('gui_beacon_data', 'r')
            lines = f.readlines()
            if not(len(lines) == 0):
                item = lines.pop(0)
                item = float(item.strip('[]\n'))
                age = item *1500*8/125000/60 
                self.age_ctrl.SetValue(str(age) + ' minutes')
            f.close()
        if os.path.exists('last_location'):
            f = open('last_location')
            lines = f.readlines()
            item = lines[0]
            [lon, lat] = item.split(',')
            lon = lon.strip('[]\n')
            lat = lat.strip('[]\n')
            self.lon_ctrl.SetValue(lon)
            self.lat_ctrl.SetValue(lat)
            f.close()
        if self.counter % 6 == 0:
            dist = random.randrange(5,300)
            dir_index = random.randrange(0,4)
            way = self.dir[dir_index]
            command = "Head " + way + " for %d meters." % dist
            self.update_msg_ctrl(command)
            self.counter = 0
        self.counter += 1
        




    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle("Field Team")
        self.SetSize((1200, 826))
        self.lat_label.SetMinSize((150, 26))
        self.lat_label.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.lat_ctrl.SetMinSize((250, 30))
        self.lat_ctrl.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.lon_label.SetMinSize((150, 26))
        self.lon_label.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.lon_ctrl.SetMinSize((250, 30))
        self.lon_ctrl.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.age_label.SetMinSize((150, 26))
        self.age_label.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.age_ctrl.SetMinSize((250, 30))
        self.age_ctrl.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.msg_label.SetMinSize((120, 26))
        self.msg_label.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.ack_button.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.act_button.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_24 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_25 = wx.BoxSizer(wx.VERTICAL)
        sizer_26 = wx.BoxSizer(wx.VERTICAL)
        sizer_29 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_28 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_27 = wx.BoxSizer(wx.HORIZONTAL)
        button_sizer = wx.BoxSizer(wx.HORIZONTAL)
        sizer_24.Add(self.picture, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_27.Add(self.lat_label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_27.Add(self.lat_ctrl, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_26.Add(sizer_27, 1, wx.EXPAND, 0)
        sizer_28.Add(self.lon_label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_28.Add(self.lon_ctrl, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_26.Add(sizer_28, 1, wx.EXPAND, 0)
        sizer_29.Add(self.age_label, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_29.Add(self.age_ctrl, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_26.Add(sizer_29, 1, wx.EXPAND, 0)
        sizer_25.Add(sizer_26, 1, wx.EXPAND, 0)
        sizer_25.Add(self.msg_label, 0, wx.LEFT, 10)
        sizer_25.Add(self.msg_panel, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 4)
        button_sizer.Add(self.ack_button, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_BOTTOM, 4)
        button_sizer.Add(self.act_button, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_BOTTOM, 4)
        sizer_25.Add(button_sizer, 0,wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_24.Add(sizer_25, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_24)
        self.Layout()
        # end wxGlade

# end of class MyFrame1

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = repeater_gui()
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
