#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Oct  5 21:59:49 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class MyNotebook(wx.Notebook):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyNotebook.__init__
        kwds["style"] = 0
        wx.Notebook.__init__(self, *args, **kwds)
        self.notebook_1_pane_2 = wx.ScrolledWindow(self, -1, style=wx.TAB_TRAVERSAL)
	
        self.notebook_1_pane_1 = wx.ScrolledWindow(self, -1, style=wx.TAB_TRAVERSAL)
        self.bitmap_1 = wx.StaticBitmap(self.notebook_1_pane_1, -1, wx.Bitmap("./image.jpg", wx.BITMAP_TYPE_ANY))
        self.label_2 = wx.StaticText(self.notebook_1_pane_1, -1, "ID #")
        self.text_ctrl_4 = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.label_3 = wx.StaticText(self.notebook_1_pane_1, -1, "Team name")
        self.text_ctrl_5 = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "Assigned frequency")
        self.text_ctrl_6 = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.label_5 = wx.StaticText(self.notebook_1_pane_1, -1, "Special skills, equipment")
        self.text_ctrl_7 = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.label_6 = wx.StaticText(self.notebook_1_pane_1, -1, "Misc notes")
        self.text_ctrl_8 = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.button_3 = wx.Button(self.notebook_1_pane_1, 10, "Acquire Radio")
        self.button_4 = wx.Button(self.notebook_1_pane_1, 11, "Register Radio")
        self.button_5 = wx.Button(self.notebook_1_pane_1, 12, "Reassign Frequencies")

        
	self.lc = wx.ListCtrl(self.notebook_1_pane_2, -1, style=wx.LC_REPORT)
	self.lc.InsertColumn(0, 'ID #')
        self.lc.InsertColumn(1, 'Team Name')
        self.lc.InsertColumn(2, 'Assigned frequency')
        self.lc.InsertColumn(3, 'Special skills, equipment')
        self.lc.InsertColumn(4, 'Misc Notes')
        self.lc.SetColumnWidth(0, 140)
        self.lc.SetColumnWidth(1, 153)
        self.lc.SetColumnWidth(2, 166)
        self.lc.SetColumnWidth(3, 179)
        self.lc.SetColumnWidth(4, 195)
        

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyNotebook.__set_properties
        self.AddPage(self.notebook_1_pane_1, "Register Radio")
        self.AddPage(self.notebook_1_pane_2, "Overview")
        self.notebook_1_pane_2.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyNotebook.__do_layout
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add((600, 20), 0, 0, 0)
        sizer_6.Add(self.label_2, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_6.Add(self.text_ctrl_4, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 2)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_7.Add(self.label_3, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_7.Add(self.text_ctrl_5, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 2)
        sizer_4.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_8.Add(self.label_4, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_8.Add(self.text_ctrl_6, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 2)
        sizer_4.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_9.Add(self.label_5, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_9.Add(self.text_ctrl_7, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 2)
        sizer_4.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_10.Add(self.label_6, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_10.Add(self.text_ctrl_8, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 2)
        sizer_4.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_11.Add(self.button_3, 10, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_11.Add(self.button_4, 11, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_11.Add(self.button_5, 12, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
	self.notebook_1_pane_1.Bind (wx.EVT_BUTTON, self.OnAdd, id=11)
        sizer_11.Add((300, 20), 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(sizer_11, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_4, 1, wx.ALL|wx.EXPAND, 3)
        self.notebook_1_pane_1.SetSizer(sizer_2)
        sizer_12.Add(self.lc, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 4)
	self.notebook_1_pane_2.SetSizer(sizer_12)
        # end wxGlade
 
    def OnAdd(self, event):
        if not self.text_ctrl_4.GetValue() or not self.text_ctrl_5.GetValue():
            return
        num_items = self.lc.GetItemCount()
        self.lc.InsertStringItem(num_items, self.text_ctrl_4.GetValue())
        self.lc.SetStringItem(num_items, 1, self.text_ctrl_5.GetValue())
        self.lc.SetStringItem(num_items, 2, self.text_ctrl_6.GetValue())
        self.lc.SetStringItem(num_items, 3, self.text_ctrl_7.GetValue())
        self.lc.SetStringItem(num_items, 4, self.text_ctrl_8.GetValue())
        self.text_ctrl_4.Clear()
        self.text_ctrl_5.Clear()
        self.text_ctrl_6.Clear()
        self.text_ctrl_7.Clear()
        self.text_ctrl_8.Clear()



# end of class MyNotebook


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = MyNotebook(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Radio Registration")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
